#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("a_vitavol.Resource", IsApplication=true)]

namespace a_vitavol
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070008
			public const int common_google_signin_btn_text_dark = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int common_google_signin_btn_text_dark_default = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int common_google_signin_btn_text_dark_disabled = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_signin_btn_text_dark_focused = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_signin_btn_text_dark_pressed = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int common_google_signin_btn_text_light = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int common_google_signin_btn_text_light_default = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_signin_btn_text_light_disabled = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int common_google_signin_btn_text_light_focused = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_google_signin_btn_text_light_pressed = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_signin_btn_tint = 2131165194;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bkgnd = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int closed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int closedboxed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_full_open_on_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_disabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_normal_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_disabled = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_normal_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int googleg_disabled_color_18 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int googleg_standard_color_18 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int opennoneeds = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int opennoneedsboxed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int openwithneeds = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int openwithneedsboxed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int riverwalk = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int riverwalk2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int vitaiconv2 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int vitavol = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001c
			public const int B_About = 2131230748;
			
			// aapt resource value: 0x7f08007f
			public const int B_CreateNewSignup = 2131230847;
			
			// aapt resource value: 0x7f08005b
			public const int B_DeleteSuggestion = 2131230811;
			
			// aapt resource value: 0x7f080067
			public const int B_GetDirections = 2131230823;
			
			// aapt resource value: 0x7f080018
			public const int B_Login = 2131230744;
			
			// aapt resource value: 0x7f08002d
			public const int B_NextMonth = 2131230765;
			
			// aapt resource value: 0x7f080081
			public const int B_PostSuggestion = 2131230849;
			
			// aapt resource value: 0x7f08002b
			public const int B_PrevMonth = 2131230763;
			
			// aapt resource value: 0x7f080023
			public const int B_Profile_Submit = 2131230755;
			
			// aapt resource value: 0x7f08001a
			public const int B_Register = 2131230746;
			
			// aapt resource value: 0x7f08002a
			public const int B_Register_Submit = 2131230762;
			
			// aapt resource value: 0x7f080068
			public const int B_RemoveThisSignup = 2131230824;
			
			// aapt resource value: 0x7f08003a
			public const int B_SCMySite_Accepting = 2131230778;
			
			// aapt resource value: 0x7f08003c
			public const int B_SCMySite_AtLimit = 2131230780;
			
			// aapt resource value: 0x7f080039
			public const int B_SCMySite_Closed = 2131230777;
			
			// aapt resource value: 0x7f080034
			public const int B_SCMySite_EditProfile = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int B_SCMySite_EditSiteCalendar = 2131230771;
			
			// aapt resource value: 0x7f080032
			public const int B_SCMySite_ManageVolunteers = 2131230770;
			
			// aapt resource value: 0x7f08003b
			public const int B_SCMySite_NearLimit = 2131230779;
			
			// aapt resource value: 0x7f080044
			public const int B_SCSiteCalShifts_SaveChanges = 2131230788;
			
			// aapt resource value: 0x7f08004a
			public const int B_SCSiteVol_ApproveHours = 2131230794;
			
			// aapt resource value: 0x7f080069
			public const int B_SaveHours = 2131230825;
			
			// aapt resource value: 0x7f08005a
			public const int B_SaveSuggestion = 2131230810;
			
			// aapt resource value: 0x7f080080
			public const int B_Suggestions = 2131230848;
			
			// aapt resource value: 0x7f080082
			public const int B_UpdateProfile = 2131230850;
			
			// aapt resource value: 0x7f08006f
			public const int B_ViewSignUpNew_GetDirections = 2131230831;
			
			// aapt resource value: 0x7f080070
			public const int B_ViewSignUpNew_SignMeUp = 2131230832;
			
			// aapt resource value: 0x7f08007a
			public const int B_ViewSitesOnMap = 2131230842;
			
			// aapt resource value: 0x7f08007e
			public const int B_ViewTodaySignups = 2131230846;
			
			// aapt resource value: 0x7f080029
			public const int CB_Register_Advanced = 2131230761;
			
			// aapt resource value: 0x7f080035
			public const int CB_SCMySite_DropOff = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int CB_SCMySite_Express = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int CB_SCMySite_MFT = 2131230775;
			
			// aapt resource value: 0x7f080045
			public const int CB_SCSiteCalShifts_SiteIsOpen = 2131230789;
			
			// aapt resource value: 0x7f08002e
			public const int GV_Calendar = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int IMG_Closed = 2131230767;
			
			// aapt resource value: 0x7f080051
			public const int IMG_FutureDateFullyStaffed = 2131230801;
			
			// aapt resource value: 0x7f080052
			public const int IMG_FutureDateHaveNeeds = 2131230802;
			
			// aapt resource value: 0x7f08004e
			public const int IMG_NoVolunteers = 2131230798;
			
			// aapt resource value: 0x7f080030
			public const int IMG_Open = 2131230768;
			
			// aapt resource value: 0x7f080073
			public const int IMG_OpenNoNeeds = 2131230835;
			
			// aapt resource value: 0x7f080075
			public const int IMG_OpenNoNeedsBoxed = 2131230837;
			
			// aapt resource value: 0x7f080072
			public const int IMG_OpenWithNeeds = 2131230834;
			
			// aapt resource value: 0x7f080074
			public const int IMG_OpenWithNeedsBoxed = 2131230836;
			
			// aapt resource value: 0x7f080050
			public const int IMG_PastDateNeedsApproval = 2131230800;
			
			// aapt resource value: 0x7f08004f
			public const int IMG_PastDateNoApprovals = 2131230799;
			
			// aapt resource value: 0x7f080046
			public const int L1234 = 2131230790;
			
			// aapt resource value: 0x7f08006a
			public const int LV_OtherVolunteers = 2131230826;
			
			// aapt resource value: 0x7f080047
			public const int LV_SCSiteShifts_Shifts = 2131230791;
			
			// aapt resource value: 0x7f08004d
			public const int LV_SCSiteVol_List = 2131230797;
			
			// aapt resource value: 0x7f08001d
			public const int LV_SignUps = 2131230749;
			
			// aapt resource value: 0x7f080071
			public const int LV_ViewSignUpNew_OtherVolunteers = 2131230833;
			
			// aapt resource value: 0x7f080078
			public const int LV_VolPickShift_Shifts = 2131230840;
			
			// aapt resource value: 0x7f08007b
			public const int LV_VolPickSite_Sites = 2131230843;
			
			// aapt resource value: 0x7f080065
			public const int L_Address = 2131230821;
			
			// aapt resource value: 0x7f080057
			public const int L_Approval = 2131230807;
			
			// aapt resource value: 0x7f080063
			public const int L_Body = 2131230819;
			
			// aapt resource value: 0x7f08000d
			public const int L_Bytes = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int L_Cell = 2131230736;
			
			// aapt resource value: 0x7f080066
			public const int L_CityStateZip = 2131230822;
			
			// aapt resource value: 0x7f08002c
			public const int L_Date = 2131230764;
			
			// aapt resource value: 0x7f080064
			public const int L_DateAndTimes = 2131230820;
			
			// aapt resource value: 0x7f080058
			public const int L_From = 2131230808;
			
			// aapt resource value: 0x7f080054
			public const int L_Phone = 2131230804;
			
			// aapt resource value: 0x7f080020
			public const int L_Profile_Email = 2131230752;
			
			// aapt resource value: 0x7f080038
			public const int L_SCMySite_ClientStatus = 2131230776;
			
			// aapt resource value: 0x7f080031
			public const int L_SCMySite_SiteName = 2131230769;
			
			// aapt resource value: 0x7f080042
			public const int L_SCSiteShifts_Date = 2131230786;
			
			// aapt resource value: 0x7f080043
			public const int L_SCSiteShifts_Site = 2131230787;
			
			// aapt resource value: 0x7f08004c
			public const int L_SCSiteVol_AdvVolunteers = 2131230796;
			
			// aapt resource value: 0x7f08004b
			public const int L_SCSiteVol_BasicVolunteers = 2131230795;
			
			// aapt resource value: 0x7f080049
			public const int L_SCSiteVol_Date = 2131230793;
			
			// aapt resource value: 0x7f080048
			public const int L_SCSiteVol_SiteName = 2131230792;
			
			// aapt resource value: 0x7f08007d
			public const int L_SignsUpToday = 2131230845;
			
			// aapt resource value: 0x7f08003d
			public const int L_Site = 2131230781;
			
			// aapt resource value: 0x7f080059
			public const int L_State = 2131230809;
			
			// aapt resource value: 0x7f080062
			public const int L_Time = 2131230818;
			
			// aapt resource value: 0x7f080053
			public const int L_User = 2131230803;
			
			// aapt resource value: 0x7f08000e
			public const int L_Version = 2131230734;
			
			// aapt resource value: 0x7f08006d
			public const int L_ViewSignUpNew_Address = 2131230829;
			
			// aapt resource value: 0x7f08006e
			public const int L_ViewSignUpNew_CityStateZip = 2131230830;
			
			// aapt resource value: 0x7f08006c
			public const int L_ViewSignUpNew_DateAndTimes = 2131230828;
			
			// aapt resource value: 0x7f08006b
			public const int L_ViewSignUpNew_Site = 2131230827;
			
			// aapt resource value: 0x7f080076
			public const int L_VolPickShift_Date = 2131230838;
			
			// aapt resource value: 0x7f080077
			public const int L_VolPickShift_Site = 2131230839;
			
			// aapt resource value: 0x7f080079
			public const int L_VolPickSite_Date = 2131230841;
			
			// aapt resource value: 0x7f08007c
			public const int Map_Sites = 2131230844;
			
			// aapt resource value: 0x7f08003f
			public const int TB_CloseTime = 2131230783;
			
			// aapt resource value: 0x7f080014
			public const int TB_Email = 2131230740;
			
			// aapt resource value: 0x7f080056
			public const int TB_Hours = 2131230806;
			
			// aapt resource value: 0x7f08005e
			public const int TB_MessageSuggestion = 2131230814;
			
			// aapt resource value: 0x7f08003e
			public const int TB_OpenTime = 2131230782;
			
			// aapt resource value: 0x7f080016
			public const int TB_Password = 2131230742;
			
			// aapt resource value: 0x7f080021
			public const int TB_Profile_Name = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int TB_Profile_Phone = 2131230754;
			
			// aapt resource value: 0x7f080024
			public const int TB_Register_Email = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int TB_Register_Name = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int TB_Register_Password = 2131230758;
			
			// aapt resource value: 0x7f080028
			public const int TB_Register_Phone = 2131230760;
			
			// aapt resource value: 0x7f080027
			public const int TB_Register_VerifyPassword = 2131230759;
			
			// aapt resource value: 0x7f08005c
			public const int TB_SubjectSuggestion = 2131230812;
			
			// aapt resource value: 0x7f080041
			public const int TB_eFilersAdv = 2131230785;
			
			// aapt resource value: 0x7f080040
			public const int TB_eFilersBasic = 2131230784;
			
			// aapt resource value: 0x7f08005f
			public const int Text = 2131230815;
			
			// aapt resource value: 0x7f080060
			public const int Text1 = 2131230816;
			
			// aapt resource value: 0x7f080061
			public const int Text2 = 2131230817;
			
			// aapt resource value: 0x7f08000f
			public const int WV_About_About = 2131230735;
			
			// aapt resource value: 0x7f080005
			public const int adjust_height = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int adjust_width = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int auto = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int dark = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int hybrid = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int icon_only = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int light = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int none = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int satellite = 2131230723;
			
			// aapt resource value: 0x7f08001e
			public const int scroll = 2131230750;
			
			// aapt resource value: 0x7f080012
			public const int space1 = 2131230738;
			
			// aapt resource value: 0x7f080017
			public const int space2 = 2131230743;
			
			// aapt resource value: 0x7f080019
			public const int space3 = 2131230745;
			
			// aapt resource value: 0x7f08001b
			public const int space4 = 2131230747;
			
			// aapt resource value: 0x7f080008
			public const int standard = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int terrain = 2131230724;
			
			// aapt resource value: 0x7f08001f
			public const int textView1 = 2131230751;
			
			// aapt resource value: 0x7f080011
			public const int textView2 = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int textView3 = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int textView4 = 2131230741;
			
			// aapt resource value: 0x7f080055
			public const int textView5 = 2131230805;
			
			// aapt resource value: 0x7f08005d
			public const int textView6 = 2131230813;
			
			// aapt resource value: 0x7f080009
			public const int wide = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int About = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GridCell = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MySignUps = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Profile = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Registration = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SCCalendar = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SCMySite = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int SCMySites = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int SCShiftDetails = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int SCSiteCalShifts = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int SCSiteShifts = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int SCSiteVol = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int SCSiteVolCalendar = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int SCVolHours = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int Suggestion = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int SuggestionCell = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int Suggestions = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int ViewNotification = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int ViewSignUpExisting = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int ViewSignUpNew = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int VolCalendar = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int VolPickShift = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int VolPickSite = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int VolPickSiteMap = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int VolunteerOptions = 2130968601;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060018
			public const int app_name = 2131099672;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_button = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_enable_title = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_notification_ticker = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_unknown_issue = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_unsupported_text = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_button = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_text = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_title = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_wear_update_text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_open_on_phone = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_signin_button_text_long = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int default_web_client_id = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int firebase_database_url = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int gcm_defaultSenderId = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int google_api_key = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int google_app_id = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int google_crash_reporting_api_key = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int google_storage_bucket = 2131099671;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
