//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vitasa {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("vitasa.AppResources.es", typeof(AppResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Main_L_Title {
            get {
                return ResourceManager.GetString("Main_L_Title", resourceCulture);
            }
        }
        
        internal static string Main_L_SubTitle {
            get {
                return ResourceManager.GetString("Main_L_SubTitle", resourceCulture);
            }
        }
        
        internal static string Main_B_List {
            get {
                return ResourceManager.GetString("Main_B_List", resourceCulture);
            }
        }
        
        internal static string Main_B_Map {
            get {
                return ResourceManager.GetString("Main_B_Map", resourceCulture);
            }
        }
        
        internal static string Main_B_BeforeYouGo {
            get {
                return ResourceManager.GetString("Main_B_BeforeYouGo", resourceCulture);
            }
        }
        
        internal static string Main_B_Feedback {
            get {
                return ResourceManager.GetString("Main_B_Feedback", resourceCulture);
            }
        }
        
        internal static string Main_B_Resources {
            get {
                return ResourceManager.GetString("Main_B_Resources", resourceCulture);
            }
        }
        
        internal static string Main_B_MyFreeTaxes {
            get {
                return ResourceManager.GetString("Main_B_MyFreeTaxes", resourceCulture);
            }
        }
        
        internal static string Main_B_211 {
            get {
                return ResourceManager.GetString("Main_B_211", resourceCulture);
            }
        }
        
        internal static string Main_B_BecomingAVolunteer {
            get {
                return ResourceManager.GetString("Main_B_BecomingAVolunteer", resourceCulture);
            }
        }
        
        internal static string Main_B_About {
            get {
                return ResourceManager.GetString("Main_B_About", resourceCulture);
            }
        }
        
        internal static string Main_N_Accepting {
            get {
                return ResourceManager.GetString("Main_N_Accepting", resourceCulture);
            }
        }
        
        internal static string Main_N_NearLimit {
            get {
                return ResourceManager.GetString("Main_N_NearLimit", resourceCulture);
            }
        }
        
        internal static string Main_N_At_Limit {
            get {
                return ResourceManager.GetString("Main_N_At Limit", resourceCulture);
            }
        }
        
        internal static string Main_N_Closed {
            get {
                return ResourceManager.GetString("Main_N_Closed", resourceCulture);
            }
        }
        
        internal static string Main_B_Directions {
            get {
                return ResourceManager.GetString("Main_B_Directions", resourceCulture);
            }
        }
        
        internal static string Suggestion_L_Suggestion {
            get {
                return ResourceManager.GetString("Suggestion_L_Suggestion", resourceCulture);
            }
        }
        
        internal static string Suggestion_L_Subject {
            get {
                return ResourceManager.GetString("Suggestion_L_Subject", resourceCulture);
            }
        }
        
        internal static string Suggestion_L_Text {
            get {
                return ResourceManager.GetString("Suggestion_L_Text", resourceCulture);
            }
        }
        
        internal static string Suggestion_B_Submit {
            get {
                return ResourceManager.GetString("Suggestion_B_Submit", resourceCulture);
            }
        }
    }
}
